packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  vue-demi: true
catalog:
  '@types/node': 24.10.4
  'typescript': 5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
